### ISSUE TITLE
DS-Form @input not emmitted

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Nitro-Styleguide#46]
The documentation clearly says if the user inputs data, it should trigger the `@input` callback. Unfortunately `@input` is called on `submit` and `reset` but not on user input.

![Screenshot (37)](https://user-images.githubusercontent.com/2110676/54302469-31526980-45c1-11e9-8982-a5aa27b4bc24.png)

**Comment by appinteractive** [comment]
As far as I can tell that’s intended to have the comparison between submits. Why not looking in the model data?

**Comment by roschaefer** [comment]
@appinteractive the `formData` data is not updated. The validations are run, obviously because I can see red validation error messages, yet the `@input` callback is not called until I hit submit. We wan't to do cross-validation *before* submit.

**Comment by appinteractive** [comment]
I will take a look 👀
